### ISSUE TITLE
Provide type-checking and alive-checking to Lua bindings

### ISSUE THREAD

**Issue by dbartolini** [dbartolini/crown#34]
In debug/development builds we want a way to generate Lua errors when the user passes parameters with the wrong type to functions. We also want to assert() in case of dead objects.

**Comment by lundmark** [comment]
My suggestion is that you create a lua-wrapper-type for all types that you want type checking for and just pad them with an identifier as the first member of each type.

So like your World-object would look like:

struct ScriptWorld {
   static const int identifier = 0xdaad1234;
   World* world;
}

And then when you fetch the light userdata you simply fetch that identifier for all types and match that against the type you're checking against.

**Comment by taylor001** [comment]
Yes, it makes sense for most types.
