### ISSUE TITLE
connection refused error

### ISSUE THREAD

**Issue by senthuran-lkn** [dbartolini/crown#68]
hi i have managed to build the project but habving issues when running
./level-editor-debug ../../../samples/01-physics/

here is the outputs:

(level-editor-debug:29795): GLib-GObject-CRITICAL **: g_value_get_object: assertion 'G_VALUE_HOLDS_OBJECT (value)' failed

** (level-editor-debug:29795): CRITICAL **: gee_abstract_collection_foreach: assertion 'self != NULL' failed
Could not connect to 127.0.0.1: Connection refused
Could not connect to 127.0.0.1: Connection refused
Error receiving data: Connection reset by peer
Error sending data: Broken pipe
Error sending data: Broken pipe
Error sending data: Broken pipe

**Comment by taylor001** [comment]
Can you pull latest and paste here the output?

**Comment by senthuran-lkn** [comment]
hi this seems fixed now, fixed now. by the way nice engine.

**Comment by dbartolini** [comment]
Thank you. :)
