### ISSUE TITLE
Downloaded binaries give me a segmentation fault

### ISSUE THREAD

**Issue by jprob** [dbartolini/crown#79]
Is this in usable state? Are there any build instructions anywhere?
I tried downloading the linux tar and executing the binary crown-release, but all I am getting is
Initializing Crown Engine 0.0.29 linux 64-bit
Segmentation fault (core dumped)
crown debug also does not work ( https://pastebin.com/0DjPwfM3 )
Other than that, the engine looks very promising! Thanks for your commitment!

**Comment by dbartolini** [comment]
You should execute the script in the root:
    
    $ ./crown

Build instructions: https://github.com/dbartolini/crown#building-and-running-level-editor

The engine is usable but far from complete.
