### ISSUE TITLE
msys2 compile error: how to fix it?

### ISSUE THREAD

**Issue by hisupersylar** [dbartolini/crown#81]
i come to the dir of crown,then run  make tools-linux-release64,then it happens:

make -j1 -R -C 3rdparty/luajit/src CC="gcc -m64" CCOPT="-O2 -fomit-frame-pointer -msse2" TARGET_SYS=Linux BUILDMODE=static
make[1]: come to “/crown-master/3rdparty/luajit/src”
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
ASM       lj_vm.o
buildvm_x86.dasc: Assembler messages:
buildvm_x86.dasc:6: error：unknown pseudo-op: `.hidden'
buildvm_x86.dasc:7: warnning：.type pseudo-op used outside of .def/.endef ignored.
buildvm_x86.dasc:7: error：junk at end of line, first unrecognized character is `l'
buildvm_x86.dasc:8: warnning：.size pseudo-op used outside of .def/.endef ignored.
buildvm_x86.dasc:8: error：junk at end of line, first unrecognized character is `l'
buildvm_x86.dasc:13: error：unknown pseudo-op: `.hidden'
buildvm_x86.dasc:14: warnning：.type pseudo-op used outside of .def/.endef ignored.
buildvm_x86.dasc:14: error：junk at end of line, first unrecognized character is `l'
.........there are many errors like this "junk at end of line, first unrecognized character is `l' ”,how to fix it?

**Comment by dbartolini** [comment]
$ export MINGW=/mingw64
    $ export PATH=$PATH:/mingw64/bin
    $ make mingw-debug64

**Comment by hisupersylar** [comment]
# @dbartolini  thanks, it works..
